---
## This playbook deploys new changes to the environment.
- hosts: all
  gather_facts: no
  roles:
    - exporter

- hosts: supports
  gather_facts: no
  roles:
    - role: zipp-node
      nodeType: entrynode

- hosts: zipps:&internal_nodes
  gather_facts: no
  vars:
    nodeType: zipp
  roles:
    - zipp-node

- hosts: zipps:&public_nodes
  gather_facts: no
  vars:
    nodeType: public-node
  roles:
    - zipp-node

- hosts: vanilla-01*
  gather_facts: no
  roles:
    - snapshotter

- hosts: metrics
  gather_facts: no
  vars:
    removeData: no
  roles:
    - metrics