---
## This playbook sets up the whole environment stack from scratch.

- hosts: metrics
  gather_facts: no
  vars:
    removeData: yes
  roles:
    - metrics

- hosts: supports
  gather_facts: no
  roles:
    - role: zipp-node
      nodeType: entrynode

- hosts: zipps:&internal_nodes
  gather_facts: no
  vars:
    nodeType: zipp
  roles:
    - zipp-node

- hosts: zipps:&public_nodes
  gather_facts: no
  vars:
    nodeType: public-node
  roles:
    - zipp-node

- hosts: vanilla-01*
  gather_facts: no
  roles:
    - snapshotter

- hosts: asset_registries
  gather_facts: no
  roles:
    - asset-registry

- hosts: lbs
  gather_facts: no
  roles:
    - lb
