package markermanager

import (
	"github.com/izuc/zipp.foundation/runtime/event"
	"github.com/izuc/zipp/packages/protocol/markers"
)

type Events struct {
	SequenceEvicted *event.Event1[markers.SequenceID]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		SequenceEvicted: event.New1[markers.SequenceID](),
	}
})
