{
 "title": "GoShimmer Debugging",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(iota_info_app, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BPS, Autopeering, Traffic, Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Block Per Second Per Type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "targets": [
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "Block Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\",block_type=\"TransactionType(1337)\"}[1m])) by (instance)",
     "legendFormat": "Transaction Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\",block_type=\"dRNG(111)\"}[1m])) by (instance)",
     "legendFormat": "dRNG Block Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\",block_type=\"faucet(2)\"}[1m])) by (instance)",
     "legendFormat": "Faucet Block Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\",block_type=\"networkdelay(189)\"}[1m])) by (instance)",
     "legendFormat": "Network Delay Block Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\",block_type=\"Statement(3)\"}[1m])) by (instance)",
     "legendFormat": "Statements Per Second {{instance}}"
    }
   ]
  },
  {
   "title": "Block Per Second Per Instance Booker",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "BPS" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesh_blocks_per_component_count{component=\"Booker\",instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "BPS {{instance}} "
    }
   ]
  },
  {
   "title": "Block Per Second Per Instance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "BPS" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesh_blocks_per_type_count{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "BPS {{instance}} "
    }
   ]
  },
  {
   "title": "Tips",
   "type": "graph",
   "description": "Shows tips in block and value layer.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesh_block_tips_count{instance=~\"$instance\"}",
     "legendFormat": "Tips {{instance}}"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "graph",
   "description": "Number of blocks in missingBlockStore. These are the block the node knows it doesn't have and tries to requests them.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesh_block_missing_count_db{instance=~\"$instance\"}",
     "legendFormat": "Missing Blocks {{instance}}"
    }
   ]
  },
  {
   "title": "Blocks in Database",
   "type": "graph",
   "description": "Describes the amount of total, solid and not solid blocks in the node's database.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesh_block_solid_count_db{instance=~\"$instance\"}",
     "legendFormat": "Solid Blocks in DB {{instance}}"
    },
    {
     "expr": "mesh_block_total_count_db{instance=~\"$instance\"} - mesh_block_solid_count_db{instance=~\"$instance\"}",
     "legendFormat": "Not Solid Blocks in DB {{instance}}"
    },
    {
     "expr": "mesh_block_total_count_db{instance=~\"$instance\"}",
     "legendFormat": "Total Blocks in DB {{instance}}"
    }
   ]
  },
  {
   "title": "Block Request Queue Size",
   "type": "graph",
   "description": "Number of blocks currently requested by the block mesh.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesh_block_request_queue_size{instance=~\"$instance\"}",
     "legendFormat": "Block Request Queue Size"
    }
   ]
  },
  {
   "title": "Average Solidification Time",
   "type": "graph",
   "description": "Average time it takes to solidify blocks.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mesh_block_avg_solidification_time{instance=~\"$instance\"}",
     "legendFormat": "Avg Solidification Time {{instance}}"
    }
   ]
  }
 ]
}