{
 "title": "ZIPP Mana Research",
 "description": "Shows mana metrics with different EBM1 & EBM2 weights.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NodeID", "label": "Node Identity", "query": "label_values(info_app, nodeID)" }
  ]
 },
 "panels": [
  {
   "title": "Access Mana $NodeID",
   "type": "graph",
   "description": "Amount of access mana this node has.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_access{nodeID=\"$NodeID\"}",
     "legendFormat": "Access Mana (Mixed)"
    },
    {
     "expr": "mana_access_per_node{nodeID=\"$NodeID\"}",
     "legendFormat": "Access Mana  (OnlyMana2)"
    }
   ]
  },
  {
   "title": "Consensus Mana $NodeID",
   "type": "graph",
   "description": "Amount of consensus mana this node has.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus{nodeID=\"$NodeID\"}",
     "legendFormat": "Consensus Mana (Mixed)"
    },
    {
     "expr": "mana_consensus_per_node{nodeID=\"$NodeID\"}",
     "legendFormat": "Consensus Mana (OnlyMana1)"
    }
   ]
  },
  {
   "title": "Access Mana Percentile Development $NodeID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mana_research_access_percentile",
     "legendFormat": "Access Percentile (Mixed)"
    },
    { "expr": "mana_node_percentile", "legendFormat": "Access Percentile (OnlyMana2)" }
   ]
  },
  {
   "title": "Consensus Mana Percentile Development $NodeID",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mana_research_consensus_percentile",
     "legendFormat": "Consensus Percentile (Mixed)"
    },
    {
     "expr": "mana_node_percentile",
     "legendFormat": "Consensus Percentile (OnlyMana1)"
    }
   ]
  },
  {
   "title": "Total Access Mana In Network",
   "type": "graph",
   "description": "Total Access  Mana In the network.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(mana_research_access)", "legendFormat": "Total Access  (Mixed)" },
    { "expr": "sum(mana_access_per_node)", "legendFormat": "Total Access (OnlyMana2)" }
   ]
  },
  {
   "title": "Total Consensus Mana In Network",
   "type": "graph",
   "description": "Total Consensus  Mana In the network.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(mana_research_consensus)", "legendFormat": "Total Consensus Mana (Mixed)" },
    {
     "expr": "sum(mana_consensus_per_node)",
     "legendFormat": "Total Consensus Mana (OnlyMana1)"
    }
   ]
  },
  {
   "title": "Average Access Mana",
   "type": "graph",
   "description": "Average access mana of a node in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(mana_research_access)", "legendFormat": "Access Mana (Mixed)" },
    { "expr": "avg(mana_access_per_node)", "legendFormat": "Access Mana (OnlyMana2)" }
   ]
  },
  {
   "title": "Average Consensus Mana",
   "type": "graph",
   "description": "Average consensus mana of a node in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(mana_research_consensus)", "legendFormat": "Consensus Mana (Mixed)" },
    { "expr": "avg(mana_consensus_per_node)", "legendFormat": "Consensus Mana (OnlyMana1)" }
   ]
  },
  {
   "title": "Standard Deviation of Access Mana",
   "type": "graph",
   "description": "Standard deviation of access mana of nodes in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stddev(mana_research_access)", "legendFormat": "Access Mana (Mixed)" },
    { "expr": "stddev(mana_access_per_node)", "legendFormat": "Access Mana (OnlyMana2)" }
   ]
  },
  {
   "title": "Standard Deviation of Consensus Mana",
   "type": "graph",
   "description": "Standard deviation of consensus mana of nodes in the network.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stddev(mana_research_consensus)",
     "legendFormat": "Consensus Mana (Mixed)"
    },
    {
     "expr": "stddev(mana_consensus_per_node)",
     "legendFormat": "Consensus Mana (OnlyMana1)"
    }
   ]
  },
  {
   "title": "Access Mana (Mixed) Distribution In Network",
   "type": "graph",
   "description": "Histogram of access mana 2 of nodes by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    { "expr": "mana_research_access" }
   ]
  },
  {
   "title": "Access Mana (OnlyMana2) Distribution In Network",
   "type": "graph",
   "description": "Histogram of access mana 2 of nodes by taking only EBM2 into account.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    { "expr": "mana_access_per_node" }
   ]
  },
  {
   "title": "Network Wide Access Mana (Mixed)",
   "type": "graph",
   "description": "Amount of access mana of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mana_research_access", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Access Mana (Mixed) Allocation",
   "type": "piechart",
   "description": "Allocation of access mana of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mana_research_access", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Network Wide Access Mana (OnlyMana2)",
   "type": "graph",
   "description": "Amount of access mana of nodes in the network by taking only EBM2 into account.",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mana_access_per_node", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Access Mana (OnlyMana2) Allocation",
   "type": "piechart",
   "description": "Allocation of access mana of nodes in the network by taking into account only EBM2.",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mana_access_per_node", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Consensus Mana (Mixed) Distribution in Network",
   "type": "graph",
   "description": "Histogram of consensus mana of nodes by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    { "expr": "mana_research_consensus" }
   ]
  },
  {
   "title": "Consensus Mana (OnlyMana1) Distribution in Network",
   "type": "graph",
   "description": "Histogram of consensus mana of nodes by only taking into account EBM1.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    { "expr": "mana_consensus_per_node" }
   ]
  },
  {
   "title": "Network Wide Consensus Mana Mixed",
   "type": "graph",
   "description": "Amount of consensus mana of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mana_research_consensus", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Consensus Mana Mixed Allocation",
   "type": "piechart",
   "description": "Allocation of consensus mana of nodes in the network by taking into account 50% EBM1 and 50% EBM2.",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mana_research_consensus", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Network Wide Consensus Mana (OnlyMana1)",
   "type": "graph",
   "description": "Amount of consensus mana of nodes in the network by taking only EBM1 into account.",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mana_consensus_per_node", "legendFormat": "{{nodeID}}" }
   ]
  },
  {
   "title": "Consensus Mana (OnlyMana1) Allocation",
   "type": "piechart",
   "description": "Allocation of consensus mana of nodes in the network by taking into account only EBM1.",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mana_consensus_per_node", "legendFormat": "{{nodeID}}" }
   ]
  }
 ]
}