package sequencetracker

import (
	"github.com/izuc/zipp.foundation/crypto/identity"
	"github.com/izuc/zipp.foundation/runtime/event"
	"github.com/izuc/zipp/packages/protocol/markers"
)

type Events struct {
	VotersUpdated *event.Event1[*VoterUpdatedEvent]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		VotersUpdated: event.New1[*VoterUpdatedEvent](),
	}
})

type VoterUpdatedEvent struct {
	Voter                 identity.ID
	NewMaxSupportedIndex  markers.Index
	PrevMaxSupportedIndex markers.Index
	SequenceID            markers.SequenceID
}
