version: "3.5"

services:
  tester:
    container_name: tester
    image: golang:1.20-bullseye
    working_dir: /tmp/zipp/tools/integration-tests/tester
    command: /tmp/assets/entrypoint.sh
    environment:
      - TEST_NAME=${TEST_NAME}
      - CURRENT_UID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../..:/tmp/zipp:rw
      - ../logs:/tmp/logs
      - ../assets:/tmp/assets
      - ~/go/pkg:/go
      - ~/go/cache:/root/.cache/go-build
      - zipp-testing-assets:/assets

volumes:
  zipp-testing-assets:
    name: zipp-testing-assets
