version: "3.5"

services:
  tester:
    container_name: tester
    image: golang:1.20-bullseye
    working_dir: /tmp/zipp/tools/integration-tests/tester
    command: /tmp/assets/entrypoint.sh
    environment:
      - DEBUG=${DEBUG}
      - TEST_NAME=${TEST_NAME}
    ports:
      - "127.0.0.1:50000:40000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../..:/tmp/zipp:rw
      - ../logs:/tmp/logs
      - ../assets:/tmp/assets
      - zipp-testing-source:/go
      - zipp-testing-cache:/root/.cache
      - zipp-testing-assets:/assets

volumes:
  zipp-testing-source:
    name: zipp-testing-source
  zipp-testing-cache:
    name: zipp-testing-cache
  zipp-testing-assets:
    name: zipp-testing-assets
