blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.zipp.org/
    about: Please ask and answer questions here.
  - name: Security vulnerabilities
    url: security@zipp.org
    about: Please report security vulnerabilities here.