package blockgadget

import (
	"github.com/izuc/zipp.foundation/ds/shrinkingmap"
	"github.com/izuc/zipp.foundation/runtime/event"
	"github.com/izuc/zipp/packages/protocol/models"
)

type Events struct {
	BlockAccepted  *event.Event1[*Block]
	BlockConfirmed *event.Event1[*Block]
	SlotClosed     *event.Event1[*shrinkingmap.ShrinkingMap[models.BlockID, *Block]]
	Error          *event.Event1[error]

	event.Group[Events, *Events]
}

// NewEvents contains the constructor of the Events object (it is generated by a generic factory).
var NewEvents = event.CreateGroupConstructor(func() (newEvents *Events) {
	return &Events{
		BlockAccepted:  event.New1[*Block](),
		BlockConfirmed: event.New1[*Block](),
		SlotClosed:     event.New1[*shrinkingmap.ShrinkingMap[models.BlockID, *Block]](),
		Error:          event.New1[error](),
	}
})
